# -*- coding: utf-8 -*-
"""05_02_언어분석_영어_심화.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19HZK7QfkLkfdVir5q_apTjKJIoyWW85S

# 환경 준비
"""

# NLTK 세팅하기 
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

import pandas as pd

"""# 데이터 불러오기"""

# 구글 드라이브 연결을 위한 기본 세팅 
!pip install -U -q PyDrive
 
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

## 문서 ID로 실제 파일 불러오기
# 실습을 위한 역대 미국 대통령 승리 연설: George Walker Bush, Barack Obama, Donald Trump
## https://drive.google.com/open?id=18efyC5TLTlvaPgWiZtYX-767jsBEZl1p
#	id	person	year	text
#	1	George Walker Bush	2000	Thank you very much.\n\nGood evening, my fello...
#	2	George Walker Bush	2004	Thank you all. Thank you all for coming. We ha...
#	3	Barack Obama	2008	Hello, Chicago.\n\nIf there is anyone out ther...
#	4	Barack Obama	2012	Thank you. Thank you. Thank you so much.\n\nTo...
#	5	Donald Trump	2016	Thank you. Thank you very much, everybody. Sor...

rawdata_downloaded = drive.CreateFile({'id': '1Aa82JE3k9Z5auHV6HjnhZdZlnbPuXgjx'})
rawdata_downloaded.GetContentFile('rawdata.csv')

# "rawdata.txt" 파일의 내용을 "원본데이터" 변수로 불러오기
원본데이터 = pd.read_csv('rawdata.csv')

# "원본데이터" 변수 내용 확인하기
원본데이터

# 형태소 분석
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')


저장공간  = []
for index, row in 원본데이터.iterrows():
    textdata = row[2]
    type = row[0]
    형태소 = nltk.tokenize.word_tokenize(textdata)
    형태소종합 = list(nltk.pos_tag(형태소))
    형태소종합 = pd.DataFrame.from_records(형태소종합)
    형태소종합['type'] = type
    형태소종합['count'] = 1      
    저장공간.append(형태소종합)

# "형태소" 변수의 저장 내용 확인
형태소

# "형태소종합" 변수의 저장 내용 확인
형태소종합

# "저장공간" 변수의 저장 내용 확인
저장공간

# "저장공간" 변수의 내용을 데이터프레임 형식으로 변환해서 "분석통합" 변수에 저장한다.
분석통합 = pd.concat(저장공간)

# "분석통합" 변수의 저장 내용 확인
분석통합

# "분석통합" 변수의 컬럼(열) 이름 변경
분석통합.columns = ["형태소", "품사", "분류", "카운트"]

# "분석통합" 변수의 저장 내용 확인
분석통합

# "분석통합" 변수의 내용을 형태소, 품사, 분류가 같은 것을 합치고, 카운트의 총합을 구해서 "그룹통합" 변수에 저장한다.
그룹통합 = 분석통합.groupby(['형태소', '품사', "분류"])['카운트'].sum()

# "그룹통합" 변수의 저장 내용 확인
그룹통합

# "그룹통합" 변수의 내용을 데이터프레임 형식으로 변환해서 "그룹통합" 변수에 저장한다.
그룹통합 = pd.DataFrame(그룹통합)

# "그룹통합" 변수의 저장 내용 확인
그룹통합

# "그룹통합" 변수의 내용을 "형태소분석결과.csv" 파일로 저장한다.
# header는 컬럼(열) 정보의 포함 여부이다.
# encoding은 문자코드를 선택하는 것이다. python에서는 기본적으로 utf-8(유니코드)를 사용한다.

그룹통합.to_csv('형태소분석결과.csv', header='true', encoding='utf-8-sig')