# -*- coding: utf-8 -*-
"""비티에스.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1laO-_eaTqwSh97Ymsg41UzIB5lNn9pTA
"""

import sys

# install chromium, its driver, and selenium
if 'google.colab' in sys.modules:
    !apt-get update
    !apt install chromium-chromedriver
    !cp /usr/lib/chromium-browser/chromedriver /usr/bin
    !pip install selenium

# set options to be headless, ..
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

data=[]

with webdriver.Chrome('chromedriver',options=options) as driver:
    wait = WebDriverWait(driver,15)
    driver.get("https://www.youtube.com/watch?v=kTlv5_Bs8aw&list=PL6Ri1UOk51t6Y11lbr0FwHfcz4DoaOilM") ## 대상 유튜브 주소 입력!

    for item in range(1000): ## 수집량 입력 --> 기본 값은 200건 수집 MIC DROP
        wait.until(EC.visibility_of_element_located((By.TAG_NAME, "body"))).send_keys(Keys.END)
        #time.sleep(15)

    for comment in wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#content"))):
        data.append(comment.text)

import pandas as pd   
결과 = pd.DataFrame(data, columns=['comment'])
결과.head()

결과.to_csv('비티에스4.csv', header='true', encoding='utf-8')